### ISSUE TITLE
/Documentation/Create Token- Token creation doc [Bounty]

### ISSUE THREAD

**Issue by miimiispets** [tronprotocol/Documentation#13]
Suggestion to add a doc outlying the basics of token creation:

Including for example

- Terms of service - regarding relationship and code of conduct between Creator and TRON network. And Creator and Investors.
- Initial offering on TRX platform - on Creation page with explanation of creation variables.
- Maintenance by Creator - on Creation/admin page? What to do in case of UI failure, contact details of TRON network support.
- Process after token creation - How Creator interacts with Investors after Token launch. For example integration wallet/token in apps etc.
- etc.

**Comment by ybhgenius** [comment]
Yes, you definitely can contribute whether in TRON docs, texts translation or other work related to TRON. You can create the doc about token creation if you are willing to do this. We will reward you according to your contribution. Please feel free to contact and send your work to trondocs@tron.network

**Comment by miimiispets** [comment]
ybhgenius. I've started with doing some translation works in the Dutch docs section (crowdin.com). By doind this gathering info for writing a "Create token" doc. Just for my info, in which way will rewards be given?

**Comment by ybhgenius** [comment]
Thanks for your message. Please leave me your email address and the rewards are usually given in TRX.

**Comment by tmao1129** [comment]
@miimiispets  Please check out the Developers API Documentation portal at https://developers.tron.network/. Also, please join the Developers Discord Channel at https://discordapp.com/invite/GsRgsTD. Thanks.
