### ISSUE TITLE
Add solidity nodes ip address for testnet 

### ISSUE THREAD

**Issue by nfleury** [tronprotocol/Documentation#132]
Currently this is the only doc for Tesnet documentation:

https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Protocol/Test_Net_of_TRON.md

But for those who don't run a node and just want to use grpc of deployed testnet nodes, it would be nice to also have the list of TRON testnet solidity nodes ips that are currently deployed just like you did for mainet with : 

https://github.com/tronprotocol/Documentation/blob/master/TRX/Official_Public_Node.md

Thanks

**Comment by tmao1129** [comment]
@nfleury  Hi, please check out https://developers.tron.network/. This is our new Developers API Documentation portal. Also, please join the TRON Developers Discord Channel at https://discordapp.com/invite/GsRgsTD. Thanks.
