### ISSUE TITLE
Community Question - IRC Channel request

### ISSUE THREAD

**Issue by sdrobertw** [tronprotocol/Documentation#200]
@tronfoundation 

Is there, or will there ever be a Tron/TRX IRC channel [1]? There are some great developer communities on IRC, I would highly recommend an official Tron channel for this platform.

Would be glad to help. 
Regards,

[1]: https://en.wikipedia.org/wiki/Internet_Relay_Chat

**Comment by kookiekrak** [comment]
@sdrobertw hmm can you point me to some for like eth? We haven't had anyone interested in an irc channel yet

**Comment by sdrobertw** [comment]
@kookiekrak 

People interact on IRC for many coins, both for development and community. If you go to Freenode Chat: https://webchat.freenode.net/

and join the following channels: #litecoin, #monero, monero-dev, #ethereum and many more, you will find a vibrant community of devs, consumers, traders, etc... 

Let me know if you have any more questions on how to use IRC.

On another note: Tron devs can set up a Slack channel and directly link the channel to an larger IRC channel to maintain communication with the community this way as well. 

Either way, this is just a thought on another way to expand such a great community.

Cheers.

**Comment by kookiekrak** [comment]
@sdrobertw Hmm got it. Want to create an IRC channel and link me to it? I'll figure out the slack integration.

You're on our slack too right?

**Comment by sdrobertw** [comment]
@kookiekrak seems I am not part of the tronfoundation Slack workspace.

Can I get an invite for the following email address: sdrobertw@gmail.com

**Comment by sdrobertw** [comment]
@kookiekrak invitation received for Slack channel. Thanks!
