### ISSUE TITLE
Withdrawal No Received

### ISSUE THREAD

**Issue by OdranOC** [tronprotocol/Documentation#233]
Not sure where this should go, but I downloaded the Tron Wallet for Android yesterday made a transfer of all my trx to the cold wallet. No sign of it anywhere even though I used the receiving address that was provided.

**Comment by OdranOC** [comment]
It was from Binance

**Comment by kookiekrak** [comment]
what address? take a look on tronscan.org

**Comment by OdranOC** [comment]
Address is TD7ZaomQK5RgCJE1ua8mo9mANtTywvosNo

However, I cannot see the TRX in my cold wallet, or if it is how to access
it.

**Comment by kookiekrak** [comment]
@OdranOC please ask binance to resend the withdraw. I don't see a record of it on tronscan

**Comment by OdranOC** [comment]
It is confirmed in the blockchain. Check out tronscan.

The problem is not with Binance its your wallet.

If this is not resolved I will never buy TRX again, in fact I was in the
process of buying 250,000 TRX until this happened and stopped the
transaction. If I cannot trust Tron and its wallets with 30000+ TRX I am
certainly not going to trust Tron with 250000 TRX.
