### ISSUE TITLE
Add command samples on TRON Virtual Machine doco's Smart Contract Deployment section.

### ISSUE THREAD

**Issue by WendySanarwanto** [tronprotocol/Documentation#278]
Guys, it would be great for smart contract developers like me if you could add command samples on this [documentation](https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Virtual_Machine/Virtual_Machine_Introduction.md)'s `smart contract deployment` section. Particularly on `3. Deploy contract` & `4. Invoke contract` steps. Many thanks in advance.

**Comment by tmao1129** [comment]
Hi @WendySanarwanto , the smart contract deployment section in the document you referenced (Virtual_Machine_Introduction.md), will be deprecated. Perhaps you can take a look at the README.md file under tronprotocol/tron-box/Contract_Deploy/README.md. That is a recently updated file that may provide better guidance. Thank you.

**Comment by WendySanarwanto** [comment]
@tmao1129 Thanks for your response. I would play around with tron-box and also follow your advice.
