### ISSUE TITLE
Withdraw not working 

### ISSUE THREAD

**Issue by ahamedbathru** [tronprotocol/Documentation#307]
Hello Team,
I am a Crypto developer and have few queries regarding the withdraw function in Tron. I am trying to withdraw Tron my exchange using the below methods

1. CreateTransaction, gettransactionsign ,BroadcastTransaction 
2.easytransferbyprivate 
I tried to withdraw using the above methods, I have got the success results (Raw Data). But the funds are not moved to the external wallet and could not find the transaction in the explorer. So it would be great if help me to get this transaction successful.

Thanks in advance

**Comment by tmao1129** [comment]
@ahamedbathru  Can you clarify, are you trying to move TRX from an exchange into your own wallet using those API calls?
