### ISSUE TITLE
add new proposal for expand energy limit

### ISSUE THREAD

**Issue by rainysiu** [tronprotocol/Documentation#313]
Now the energy upper limit is 50_000_000_000, it's not enough, can it expand to 500_000_000_000?
Thanks!

**Comment by tmao1129** [comment]
@rainysiu  Hi, can you clarify on why the energy upper limit is not enough? Have you run into an issue during development that is related to the energy issue? Also, please be sure to join our TRON Developers Discord channel at: https://discordapp.com/invite/GsRgsTD. Thx

**Comment by tmao1129** [comment]
@rainysiu : does Tronbet have business rep or account manager who can communicate these concerns to Tron besides through GitHub? Like an official line for communicating? Discussions regarding increasing the energy limit is a fairly significant change.
