### ISSUE TITLE
Requesting TRX not working

### ISSUE THREAD

**Issue by martono91** [tronprotocol/Documentation#34]
Hi,

I have tried to sign up Tron in tronscan.org to test how does the representative voting idea works.
But turns out when i request the trx i did not get the initial 10,000k tokens as mentioned in the tron page.
Below is the address i used when i request a trx token, 
27XUvX7j1pFK6VZqNJz85jAJQXPGDzmAMfp.

To make sure something is not right I even tried to create a second account just to confirm it and it still gave the same results.

Below is also 1 of the error when I tried to participate on the token (with 0 token i have).
![image](https://user-images.githubusercontent.com/38832652/39405610-a691f9fe-4bda-11e8-95e0-674a8995b834.png)

**Comment by loganxart** [comment]
Same Problem. Hit the request button. Says I have already requested TRX for address.

No Tron to be found.

**Comment by loganxart** [comment]
Any answer to be found for this issue. Day 3.

**Comment by loganxart** [comment]
Rovak, changing accounts doesnt work for me. I prefer to have this account as the screenname is me. It leads back to me. I own it. In the spirit of transparity and openness, I would like to have this account receive the TRX.

**Comment by Rovak** [comment]
@loganxart i mean create a new account on the https://tronscan.org/#/login page

**Comment by loganxart** [comment]
Yes, got it. Thank You.

**Comment by martono91** [comment]
Problem fixed, case closed

**Comment by wuno** [comment]
When I login to, https://test.tronscan.org/#/account there is no option to request test TRX anymore. Regardless, I was never able to actually receive test TRX as every time I tried it would show the error that this thread was originally created for. Now when I go to try the ability has been completely removed from the page. 

Does anyone know how to receive test TRX so I can test our D-App?
