### ISSUE TITLE
交易多时广播成功，但是区块上查不到

### ISSUE THREAD

**Issue by zhp1254** [tronprotocol/documentation#352]
1、wallet/broadcasttransaction接口返回成功
2、wallet/gettransactionsign 当时也能查到交易（1执行完后立即执行的这个接口）

3、问题是：过一段时间后区块浏览器上没有该交易，再用wallet/gettransactionsign也查不到了，用同样的数据再调用wallet/broadcasttransaction就报DUP_TRANSACTION_ERROR，出现频率随机

想要解决的问题
4、如何避免这个问题？
5、我这个交易到底有没有广播成功？

**Comment by kevinLee2015** [comment]
You can use the 'ret' data in /wallet/gettransactionbyid to check the status of the transaction status.

**Comment by andelf** [comment]
Closed for no response.
Feel free to re-open or open-new if you have any other questions.
