### ISSUE TITLE
广播报签名错误

### ISSUE THREAD

**Issue by kongliang95** [tronprotocol/documentation#353]
{"raw_data":{"contract":[{"parameter":{"type_url":"type.googleapis.com/protocol.TransferContract","value":{"amount":100000000,"owner_address":"41aed8b191c49361e54ba57552364bcaf0080e2904","toAddress":"41dfa234a54a2e29d0996557d8f7919d3777efe229"}},"type":"TransferContract"}],"expiration":1554314754000,"ref_block_bytes":"e017","ref_block_hash":"22363f3c30bfb063","timestamp":1554278757201},"signature":["30319d7ed60268059a3f7926473747108325e0f1775e9b012624cadc3847dac815d4b9bf109e9f68b4db9953b54362b9c7bc58e3a3e2700751f5e8689513afb601"],"txID":"2a56e744e6b69295673ead36085e5100865dd1d38853cb1ad883e1e3ee9bbfdd"}
交易数据哪里错了

**Comment by boughanmiadel** [comment]
Bonjour je demande le désabonnement a ce jour 
 

Envoyé: mercredi 3 avril 2019 à 10:08
De: "kongliang95" <notifications@github.com>
À: tronprotocol/documentation <documentation@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Objet: [tronprotocol/documentation] 广播报签名错误 (#353)


{"raw_data":{"contract":[{"parameter":{"type_url":"type.googleapis.com/protocol.TransferContract","value":{"amount":100000000,"owner_address":"41aed8b191c49361e54ba57552364bcaf0080e2904","toAddress":"41dfa234a54a2e29d0996557d8f7919d3777efe229"}},"type":"TransferContract"}],"expiration":1554314754000,"ref_block_bytes":"e017","ref_block_hash":"22363f3c30bfb063","timestamp":1554278757201},"signature":["30319d7ed60268059a3f7926473747108325e0f1775e9b012624cadc3847dac815d4b9bf109e9f68b4db9953b54362b9c7bc58e3a3e2700751f5e8689513afb601"],"txID":"2a56e744e6b69295673ead36085e5100865dd1d38853cb1ad883e1e3ee9bbfdd"}
交易数据哪里错了

**Comment by kevinLee2015** [comment]
Can you provide more information and the error message?

**Comment by andelf** [comment]
Closed for no response.
Feel free to re-open or open-new if you can provide more details or have any other questions.
