### ISSUE TITLE
Http API   /walletsolidity/getblockbynum获取的区块中没有交易信息

### ISSUE THREAD

**Issue by jerry-sl** [tronprotocol/documentation#360]
运行命令：  ` curl -X POST  http://127.0.0.1:8091/walletsolidity/getblockbynum -d '{"num": 100}'`

结果：
`{
    "blockID":"000000000000006459a4898c4ada4282e5004b1744f29d944e581810bb838526",
    "block_header":{
        "raw_data":{
            "number":100,
            "txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000",
            "witness_address":"41daf91ea1770222145d6f73f84c3ecc99499242e3",
            "parentHash":"0000000000000063aed8fead595dd4ece8c3cc2f5fcd4c580867001b2f219759",
            "version":7,
            "timestamp":1552448817000
        },
        "witness_signature":"9cdad911568095723f2a4ebae2e5d9da8b2849f43f0a8614eff4728c8fd48fb86434de54d5cc7c47548af9bfb2587fa7c6d5eba13f2ff4be993008b7a8b808bc00"
    }
}
`

结果中只有blockId和blockHeader. 如果这个接口只返回这两个信息，那么我要怎么样才能根据blockNumber获取块中的交易列表。

**Comment by boughanmiadel** [comment]
Bonjour,

je demande mon désabonnement total je ne veux plus recevoir vos message à ce jour merci.

 

Envoyé: jeudi 13 juin 2019 à 09:53
De: "Sun Lei" <notifications@github.com>
À: tronprotocol/documentation <documentation@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Objet: [tronprotocol/documentation] Http API /walletsolidity/getblockbynum获取的区块中没有交易信息 (#360)


运行命令：  curl -X POST http://127.0.0.1:8091/walletsolidity/getblockbynum -d '{"num": 100}'

结果：
{ "blockID":"000000000000006459a4898c4ada4282e5004b1744f29d944e581810bb838526", "block_header":{ "raw_data":{ "number":100, "txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000", "witness_address":"41daf91ea1770222145d6f73f84c3ecc99499242e3", "parentHash":"0000000000000063aed8fead595dd4ece8c3cc2f5fcd4c580867001b2f219759", "version":7, "timestamp":1552448817000 }, "witness_signature":"9cdad911568095723f2a4ebae2e5d9da8b2849f43f0a8614eff4728c8fd48fb86434de54d5cc7c47548af9bfb2587fa7c6d5eba13f2ff4be993008b7a8b808bc00" } } 

结果中只有blockId和blockHeader. 如果这个接口只返回这两个信息，那么我要怎么样才能根据blockNumber获取块中的交易列表。
