### ISSUE TITLE
Unsynchronized block

### ISSUE THREAD

**Issue by love386** [tronprotocol/documentation#362]
version
/trx/Python-3.7.1# tron-cli version
[ TRON-CLI ]: Version:...
    1.0.5
ⓘ: Upgrade to latest version:
    pip install troncli --upgrade

At present, the block 10705315 has been synchronized.

**Comment by love386** [comment]
![image](https://user-images.githubusercontent.com/45838695/62407369-06a59380-b5ea-11e9-910f-380850867e57.png)

**Comment by love386** [comment]
[PeerServerThread] [i.n.b.ServerBootstrap](Slf4JLogger.java:146) Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x0046ec0b]'

**Comment by shydesky** [comment]
It seems that the tron-cli only supported Tron Odessey-3.6.1 which announced in the project repository https://github.com/TRON-US/tron-cli,

**Comment by andelf** [comment]
Closed for no response.
Feel free to re-open or open-new at `java-tron` or `documentation-en` repo if you have any other questions.
