### ISSUE TITLE
Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed

### ISSUE THREAD

**Issue by ksemaev** [tronprotocol/documentation#363]
Trying to run Full node on ubuntu or alpine from release Odyssey-v3.6.1 with openjdk8 and receive:

> 11:50:21.410 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:544) Exception encountered during context initialization - cancelling refresh attempt
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.messagehandler.BlockMsgHandler.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.core.net.TronNetDelegate.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/tron/FullNode.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.tron.core.db.Manager]: : Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair

Please advice!

**Comment by shydesky** [comment]
openjdk8 is not supported very well, replace with the Oracle JDK

**Comment by andelf** [comment]
Closed for no response.
Feel free to re-open or open-new if you have any other questions.
