### ISSUE TITLE
测试网同步节点失败 P2P_DISCONNECT  testnet FullNode  sync with blocks failed

### ISSUE THREAD

**Issue by youngqqcn** [tronprotocol/documentation#366]
测试网同步全节点失败, 所有的对端节点都拒绝连接, 拒绝连接:  TOO_MANY_PEERS
sync with testnet fullnode failed,  but all peers refused the connection , reason: TOO_MANY_PEERS
```
Handshake Receive from /47.252.81.126:18888, type: P2P_DISCONNECT
reason: TOO_MANY_PEERS
.....
```

哪位大兄弟知道如何解决这个问题? 
Hi guys, How can i solove this problem?

**Comment by shydesky** [comment]
choose last several seed nodes as active nodes and update them in the "active.node" item of the config.conf

**Comment by andelf** [comment]
Closed for no response.
Feel free to re-open or open-new at `java-tron` or `documentation-en` repo if you have any other questions.

**Comment by kevinchangg** [comment]
I have the same problem. How to solve it?

**Comment by youngqqcn** [comment]
> I have the same problem. How to solve it?

It's a long time ago, I forgot about it. The Tron node is very big and needs high-performance hardware. 

So, I suggest you use Tron public node instead.
