### ISSUE TITLE
如何获取交易的fromAddress, toAddress, amount? GetTransaction这类接口都没有支持

### ISSUE THREAD

**Issue by apa7** [tronprotocol/documentation#367]

**Comment by apa7** [comment]
使用MongoDb插件已解决问题.
Mongo配置
https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Event_Subscribe/mongodb_deploy.md
事件插件
https://github.com/tronprotocol/event-plugin
事件查询
https://github.com/tronprotocol/tron-eventquery

**Comment by boughanmiadel** [comment]
Désabonnement je ne veux plus recevoir vos offres elle ne m'intéresse plus merci
 

Envoyé: mardi 19 novembre 2019 à 05:36
De: "Apa7" <notifications@github.com>
À: tronprotocol/documentation <documentation@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Objet: Re: [tronprotocol/documentation] 如何获取交易的fromAddress, toAddress, amount? GetTransaction这类接口都没有支持 (#367)


Closed #367.
