### ISSUE TITLE
Is raw_data_hex the actual bandwidth? How to calculate the bandwidth from my transaction?

### ISSUE THREAD

**Issue by LmingXie** [tronprotocol/documentation#370]
_`Bandwidth_ Points
交易以字节数组的形式在网络中传输及存储，一条交易消耗的Bandwidth Points = 交易字节数 * Bandwidth Points费率。当前Bandwidth Points费率 = 1。

如一条交易的字节数组长度为200，那么该交易需要消耗200 Bandwidth Points。

注意 由于网络中总冻结资金以及账户的冻结资金随时可能发生变化，因此账户拥有的Bandwidth Points不是固定值。`

发现在转账1.12 TRX时，交易的raw_data_hex长度=266，而通过区块浏览器查询到所消耗的带宽为267。
在转账0.000001TRX时，交易的raw_data_hex长度=262，而通过区块浏览器查询到所消耗的带宽为265。
区块浏览器展示（翻个墙）：
![1581588332](https://user-images.githubusercontent.com/43197840/74423842-e190b800-4e8b-11ea-8231-3db66a155882.jpg)

**Comment by LmingXie** [comment]
转账0.000001时的交易：
https://shasta.tronscan.org/#/transaction/204a4e05ec0613004e97b8b4ee0deeff99a6eae946850be079a0ddbc166b06ff

对交易签名：
`{
	"to_address": "41d5d30398aedfb1f418a73fbb18203f456d37f480", 
	"owner_address": "419a4da92ce3367f6d550c76c5e95eb4aa2dc61e7c",
	"amount": 1
}`

签名结果：
`{"visible":false,"txID":"0bacaaf4d7de9f567cf3dc43f8149c6b63400f4195526be381eb28cf604e4b27","raw_data":{"contract":[{"parameter":{"value":{"amount":1,"owner_address":"419a4da92ce3367f6d550c76c5e95eb4aa2dc61e7c","to_address":"41d5d30398aedfb1f418a73fbb18203f456d37f480"},"type_url":"type.googleapis.com/protocol.TransferContract"},"type":"TransferContract"}],"ref_block_bytes":"7656","ref_block_hash":"b2e5c84691f5dc06","expiration":1581587910000,"timestamp":1581587851079},"raw_data_hex":"0a0276562208b2e5c84691f5dc0640f09af1ef832e5a65080112610a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412300a15419a4da92ce3367f6d550c76c5e95eb4aa2dc61e7c121541d5d30398aedfb1f418a73fbb18203f456d37f480180170c7ceedef832e"}
`

**Comment by LmingXie** [comment]
![1581588332](https://user-images.githubusercontent.com/43197840/74423648-91195a80-4e8b-11ea-96a3-9b4ddee56f45.jpg)

**Comment by andelf** [comment]
首先你好像混淆了 Hex 表示的二进制长度。

计算 bandwidth 时候有如下要点：
- 最终上链的 Transaction 结构数据（这时候包括你的 raw_data 和对 raw_data 的签名）序列化二进制长度
- Transaction 的 Result 占用
    ```java
    public static final long MAX_RESULT_SIZE_IN_TX = 64; // max 8 * 8 items in result
    ```
- 以上两者相加

-----

Raw data's length is binary length, not the hex length. You should divide it by 2. 

To calculate the accurate bandwidth:

- Serialize the Transaction (including raw transaction, transactionRet, signature, now the Transaction.raw)
- Add the bandwidth that the transaction result consumed:
    ```java
    public static final long MAX_RESULT_SIZE_IN_TX = 64; // max 8 * 8 items in result
    ```
- Now you get the actual bandwidth.

**Comment by andelf** [comment]
Close for no response.
feel free to re-open or open-new. 😄

**Comment by LmingXie** [comment]
是的，感谢你的评论。

通过下面的实例计算出了正确的带宽：

---
    @Test
    public void computingBandwidth() {
        WalletGrpc.WalletBlockingStub blockingSideStubFull = WalletGrpc.newBlockingStub(ManagedChannelBuilder.forTarget(Configuration.getByPath("config.conf")
                .getStringList("fullnode.ip.list").get(0))
                .usePlaintext(true)
                .build());

        ByteString bsTxid = ByteString.copyFrom(ByteArray.fromHexString("204a4e05ec0613004e97b8b4ee0deeff99a6eae946850be079a0ddbc166b06ff"));
        GrpcAPI.BytesMessage request = GrpcAPI.BytesMessage.newBuilder().setValue(bsTxid).build();
        Protocol.Transaction transaction = blockingSideStubFull.getTransactionById(request);

        final String transactionHexStr = ByteArray.toHexString(transaction.toByteArray());
        log.info("消耗的带宽为：{}", transactionHexStr.length() / 2 + 60);
    }
---

**Comment by DmytroShalaiev** [comment]
Please any node js example
