### ISSUE TITLE
non riesco a visualizzare il saldo del mio portafoglio

### ISSUE THREAD

**Issue by 45lab** [tronprotocol/documentation#376]

**Comment by 45lab** [comment]
non riesco ad visualizzar

**Comment by 45lab** [comment]
vorrei sapere il saldo del mio valet
t Romeo.52

**Comment by boughanmiadel** [comment]
Désabonnement je ne suis pas intéressé 

Envoyé: mercredi 23 septembre 2020 à 09:26
De: "45lab" <notifications@github.com>
À: "tronprotocol/documentation" <documentation@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Objet: Re: [tronprotocol/documentation] non riesco a visualizzare il saldo del mio portafoglio (#376)


 

vorrei sapere il saldo del mio valet
t Romeo.52
