### ISSUE TITLE
rpc GetBlockBalanceTrace(BlockBalanceTrace.BlockIdentifier)  doesn't work

### ISSUE THREAD

**Issue by ahsoliman20** [tronprotocol/documentation#410]
Does this rpc  api method still being supported?

```
  rpc GetBlockBalanceTrace (BlockBalanceTrace.BlockIdentifier) returns (BlockBalanceTrace) {
    option (google.api.http) = {
      post: "/wallet/getblockbalancetrace"
      body: "*"
      additional_bindings {
        get: "/wallet/getblockbalancetrace"
      }
    };
  };
```

Because my client receive an error while calling it using grpc. The following is the error snippet
``` 
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = ""
        debug_error_string = "{"created":"@1638115941.33131254","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"","grpc_status":2}"
```

**Comment by Benson0224** [comment]
Yes. 
Please share the address and port info of your GPRC service, thanks.

**Comment by Benson0224** [comment]
https://github.com/tronprotocol/documentation-en/blob/master/docs/api/rpc.md 
Please find all the supported GRPC API here

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks
