### ISSUE TITLE
How do big exchanges manage the wallets of the users?  

### ISSUE THREAD

**Issue by ramincsy2** [tronprotocol/documentation#424]
How do big exchanges manage the wallets of the users?

for example: when we want to withdraw TRC20 from our wallets we need to pay fee in TRX, which causes a large amount of fee that is not an economic way for us. wold you please offer any solution for this.

**Comment by Natisart** [comment]
แล้วจะต้องทำยังไง?? ถึงจะถอนเหรียญออกมาได้

**Comment by laurenceja** [comment]
Exchanges may stake for energy/bandwidth, and then they can delegate energy/bandwidth to user's account to save transaction fee.
