### ISSUE TITLE
Service stopped at block 24666235

### ISSUE THREAD

**Issue by dadaqq1** [tronprotocol/documentation#428]
Service stopped at block 24666235

https://event.nileex.io/transfers
![截屏2022-03-18 15 33 27](https://user-images.githubusercontent.com/74414043/158956842-214aacb4-1181-4622-a7e7-9900e3640f4d.png)

**Comment by amin1419** [comment]
Confirm

**Comment by hmKawsar1234** [comment]
[https://github.com/tronprotocol/documentation/issues/428#issuecomment-1072366896]()

**Comment by laurenceja** [comment]
If the node stoped syncing, you can check the node status according this [guide](https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization), or  maybe the node should be upgraded to the latest version. For deploying node on Nile testnet, please downloading the [snapshot](https://nileex.io/join/getJoinPage#about-database-backup) first, then to start the node.
