### ISSUE TITLE
TRX in Test Account.

### ISSUE THREAD

**Issue by loganxart** [tronprotocol/Documentation#52]
I have TRX in account for votes. Voting page says "Too many votes"

Wont allow me to Vote. Created new account, same issue.

![screenshot 936](https://user-images.githubusercontent.com/35274534/39936988-5e4d2128-551c-11e8-99a9-20f4e9a5adee.png)

**Comment by Jacob8765** [comment]
Can you please open this issue in the wallet-web repository?
