### ISSUE TITLE
Duplicate records and event indexing

### ISSUE THREAD

**Issue by Himanityagi27** [tronprotocol/Documentation#533]
I setup mongodb as event plugin deployment in tron , setup using the docs ..
what i have noticed is
1. there are lots of duplicate records ie same tx record occurring twice in the entire block record.
2. there is no event_Index for the tx record.

Any suggestions , How i solved this issue ..

**Comment by bradstevens1** [comment]
Hello  @Himanityagi27 
 It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID TRO07638
Please see the link below to our dedicated support line:
[Tron Support Requests ](https://dappsblockchainsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate

**Comment by thuthu24** [comment]
TFrPnTJ4smGnyjF5eTWP6GSKGHdjThELiW

**Comment by laurenceja** [comment]
@Himanityagi27 Please try to subscribe the solidified event, then only the events in the solidified block will be sent to the mongodb.
