### ISSUE TITLE
# Full Node

### ISSUE THREAD

**Issue by meemijung** [tronprotocol/Documentation#543]
# Full Node
* GRPC port: 50051
* P2P network port: 18888
* HTTP port : 8090
```
3.225.171.164
52.53.189.99
18.196.99.16
34.253.187.192
18.133.82.227
35.180.51.163
54.252.224.209
18.231.27.82
52.15.93.92
34.220.77.106
15.207.144.3
13.124.62.58
15.222.19.181
18.209.42.127
3.218.137.187
34.237.210.82
13.228.119.63
18.139.193.235
18.141.79.38
18.139.248.26
```

_Originally posted by @meemijung in https://github.com/tronprotocol/documentation/issues/540#issuecomment-2403990655_

**Comment by laurenceja** [comment]
@meemijung  We can find the mainnet nodes information [here](https://developers.tron.network/docs/networks) .
