### ISSUE TITLE
Transactions from subwallets

### ISSUE THREAD

**Issue by BigUhoTape** [tronprotocol/Documentation#548]
Hello
I have one main account (wallet)
I already create and activate subaccounts (suwallets)
What did I need to do to make transactions from subwallets, but at the same time the energy was conducted with the main wallet?
Thank you

**Comment by BigUhoTape** [comment]
`<?php

namespace app\services;

use app\components\TronComponent;
use app\models\UserWallet;

class TronService {

    private static function serviceError (): string {
        return '[TRON SERVICE ERROR]: ';
    }

    public static function createUserWallet (int $user_id): UserWallet|null {
        try {
            /** @var $tron TronComponent */
            $tron = \Yii::$app->tron;

            $create_account_result = $tron->createAccount();
            if (!$create_account_result->isSuccessful()) {
                \Yii::error(self::serviceError() . $create_account_result->getError());
                return null;
            }
            $data = $create_account_result->getData();
            $address = $data['wallet']['address_base58'] ?? null;
            if (!$address) {
                \Yii::error(self::serviceError() . 'No address!');
                return null;
            }
            $public_key = $data['wallet']['public_key'] ?? null;
            if (!$public_key) {
                \Yii::error(self::serviceError() . 'No public key!');
                return null;
            }
            $private_key = $data['wallet']['private_key'] ?? null;
            if (!$private_key) {
                \Yii::error(self::serviceError() . 'No private key!');
                return null;
            }
            $address_hex = $data['wallet']['address_hex'] ?? null;
            if (!$address_hex) {
                \Yii::error(self::serviceError() . 'No address hex!');
                return null;
            }
            $tx_id = $data['response']['txID'] ?? null;
            if (!$tx_id) {
                \Yii::error(self::serviceError() . 'No tx id!');
                return null;
            }

            $activate_account_result = $tron->sendTransaction($tron->wallet['address'], $address, 1, $tron->wallet['private_key']);
            if (!$activate_account_result->isSuccessful()) {
                \Yii::error(self::serviceError() . 'Cannot activate wallet!' . ' ' . $activate_account_result->getError());
                return null;
            }

            $user_wallet = new UserWallet();
            $user_wallet->user_id = $user_id;
            $user_wallet->address = $address;
            $user_wallet->public_key = $public_key;
            $user_wallet->setPrivateKey($private_key);
            $user_wallet->address_hex = $address_hex;
            $user_wallet->tx_id = $tx_id;

            if (!$user_wallet->save()) {
                \Yii::error(self::serviceError() . json_encode($user_wallet->getErrors()));
                return null;
            }

            return $user_wallet;
        } catch (\Exception $e) {
            \Yii::error(self::serviceError() . json_encode($e));
            return null;
        }
    }

}`

`<?php

namespace app\components;

use app\utils\ResultMessage;
use yii\base\Component;
use yii\httpclient\Client;
use IEXBase\TronAPI\Tron;
use IEXBase\TronAPI\Provider\HttpProvider;
use yii\httpclient\Response;

class TronComponent extends Component {

    public string $api_url;
    public string $api_key;
    public array $wallet;

    public function createAccount (): ResultMessage {
        try {
            $tron = $this->getTron();
            $tron_address = $tron->generateAddress();
            $new_address = $tron_address->getRawData()['address_base58'];

            $url = $this->api_url .'/wallet/createaccount';
            $data = json_encode([
                'owner_address' => $this->wallet['address'],
                'account_address' => $new_address,
                'visible' => true,
            ]);

            $client = new Client();
            $response = $client->createRequest()
                ->setMethod('POST')
                ->setUrl($url)
                ->setHeaders($this->getHeaders())
                ->setContent($data)
                ->send();

            $response = $this->processResponse($response);
            if (!$response->isSuccessful()) {
                return $response;
            }

            return ResultMessage::successful([
                'wallet' => $tron_address->getRawData(),
                'response' => $response->getData(),
            ]);
        } catch (\Exception $e) {
            return ResultMessage::fail(json_encode($e));
        }
    }

    public function sendTransaction (string $from, string $to, float $amount, string $private_key): ResultMessage {
        try {
            $tron = $this->getTron();
            $tron->setPrivateKey($private_key);

            $transaction = $tron->getTransactionBuilder()->sendTrx(
                $to,
                $amount,
                $from
            );

            $signedTransaction = $tron->signTransaction($transaction);

            $url = $this->api_url . '/wallet/broadcasttransaction';
            $client = new Client();
            $response = $client->createRequest()
                ->setMethod('POST')
                ->setUrl($url)
                ->setHeaders($this->getHeaders())
                ->setContent(json_encode($signedTransaction))
                ->send();
            return $this->processTransactionResponse($response);
        } catch (\Exception $e) {
            return ResultMessage::fail(json_encode($e));
        }
    }

    private function getTron (): Tron {
        $full_node = new HttpProvider($this->api_url);
        $solidity_node = new HttpProvider($this->api_url);
        $event_server = new HttpProvider($this->api_url);
        return new Tron($full_node, $solidity_node, $event_server);
    }

    private function getHeaders (): array {
        return [
            'accept' => 'application/json',
            'content-type' => 'application/json',
            'Tron-Pro-Api-Key' => $this->api_key
        ];
    }

    private function processResponse (Response $response): ResultMessage {
        if (!$response->isOk) {
            return ResultMessage::fail(json_encode($response));
        }

        $content = json_decode($response->getContent());
        $content = json_decode(json_encode($content), true);

        \Yii::error('TRON API RESPONSE: ' . json_encode($content));

        if ($content['Error'] ?? null) {
            return ResultMessage::fail(json_encode($content['Error']));
        }

        if (isset($content['code']) && $content['code'] == 'SIGERROR') {
            return ResultMessage::fail(json_encode($content['code']));
        }

        return ResultMessage::successful($content);
    }

    private function processTransactionResponse (Response $response): ResultMessage {
        if (!$response->isOk) {
            return ResultMessage::fail(json_encode($response));
        }

        $content = json_decode($response->getContent());
        $content = json_decode(json_encode($content), true);

        \Yii::error('TRON API RESPONSE: ' . json_encode($content));

        if ($content['Error'] ?? null) {
            return ResultMessage::fail(json_encode($content['Error']));
        }

        if (isset($content['code']) && $content['code'] == 'SIGERROR') {
            return ResultMessage::fail(json_encode($content));
        }

        if (isset($content['result']) && !$content['result']) {
            return ResultMessage::fail(json_encode($content));
        }

        return ResultMessage::successful($content);
    }
}`

Thats how i create and active subwallets

**Comment by laurenceja** [comment]
@BigUhoTape You can change the subwallets account permission, make the wallet has the permission to operate the subwallet, then you can use the multi-signature feature to operate subwallet and the energy or fees will be paid by the main wallet. https://developers.tron.network/docs/multi-signature
