### ISSUE TITLE
Migration documentation question

### ISSUE THREAD

**Issue by blacktexto** [tronprotocol/Documentation#64]
On the documentation to generate an address from the privatekey on step 5 you have the following variable:

P = 5ed0ec89eaec33d359b0632624b299d1174ee2aec5a625a3ce9145dd2ba4e48e049327d454fbf7ec700a9464f87dc4b73a592e27fd0d6d1fe7faf302e9f63306

On the next step you apply sha256(P) and according to the documentation the result is:

Hash = c7bcfe2713a76a15afa7ed84f25675b364b0e45e2668c1cdd59370136ad8ec2f

At this step if I apply sha256(P) I don't get the same result. Instead I get this hash:

Hash = 65551c712f0e301ba0ae5867f8f770e48f35791d177e4bda3edabdf714b5cdf5

You can try it on: https://emn178.github.io/online-tools/sha3_256.html

Can someone confirm if there is an error on the documentation ?

**Comment by zergweak** [comment]
HI，I thinke you made two mistakes.
1.  We are need use keccak-256.
2. We need to calculate the hash of public key by byteArray format instead of hexString.

**Comment by blacktexto** [comment]
Thanks for the answer. Can you try it and see if you have the expected result ?

**Comment by kookiekrak** [comment]
@blacktexto Hey, if you want, send me an email at tian@tron.network and I can send you an invite to our developer slack. Might get a better answer there!
