### ISSUE TITLE
how to call rpc-api

### ISSUE THREAD

**Issue by xudong7930** [tronprotocol/Documentation#65]
how to call rpc-api via curl? is there an example?

**Comment by kookiekrak** [comment]
@xudong7930 Hi, you're welcome to join our developer slack. There's people who'll be able to answer better there! Send me an email at tian@tron.network for a slack invite.

**Comment by LeetJoe** [comment]
@kookiekrak Failed to send email from China using outlook.
Is the email address valid?

**Comment by kookiekrak** [comment]
@xudong7930 please use the https://github.com/tronprotocol/grpc-gateway 

https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-overview.md#422-http-interface
