### ISSUE TITLE
BTC withdrawal requires 40 digit to be able to click SUBMIT

### ISSUE THREAD

**Issue by bennethcc** [tronprotocol/Documentation#71]
I've been on this for days now, please HELP ME..! Immediately I registered on tron.network(personalcenter) I transfered 100USD in BTC to my wallet in an attempt to purchase trx. Now I've learned how to get trx from Binance but my 100Dollars is still stuck in the BTC part of my wallet. I have over 100TRX on the TRX part of the wallet but if I want to withdraw the BTC I can't submit because the address requires 40 digits for me to be able to click submit and btc address is usually 34 digits. Ive been able to transfer the ETH and TRX which is up to 40 but not BTC. What do I do?

**Comment by ano778** [comment]
Nice frojeck

**Comment by kookiekrak** [comment]
@bennethcc 
Thank you for the bug report and sorry for the inconvenience. We'll look into this right away.

**Comment by kookiekrak** [comment]
@bennethcc The issue should be fixed now and it should no longer block you from trying to withdraw. 

I'm very sorry that this issue wasn't addressed for such a long time.

Thank you again for reporting it to us.
