### ISSUE TITLE
Bug Bounty -- What versions?

### ISSUE THREAD

**Issue by lannocc** [tronprotocol/Documentation#91]
Regarding the Bug Bounty announcement (https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_BUG-BOUNTY_Program/TRON_BUG-BOUNTY_Program.md), I failed to see any indication of which branches/revisions of the source code are meant to be audited and eligible for the bounty. Is there a specific release version I should be focused on, or does the Develop branch HEAD also qualify? Thanks.

**Comment by HaoqiZhao** [comment]
Newest Released Version Odyssey 2.0.1 for now.
